services:
    artemis-android-e2e:
        image: harbor.ase.in.tum.de/artemis-android/application:${ANDROID_APP_VERSION_TAG}
        depends_on:
            - artemis-app-setup
        environment:
            - USER_1_USERNAME=aa01aaa
            - USER_1_PASSWORD=test_user_1_password
            - USER_2_USERNAME=aa02aaa
            - USER_2_DISPLAY_NAME=Test User2
            - USER_3_USERNAME=aa03aaa
            - SERVER_URL=http://artemis-app:8080
            - DEFAULT_TIMEOUT=10000
            - ADMIN_USERNAME=artemis_admin
            - ADMIN_PASSWORD=artemis_admin
            - robolectric.logging.enabled=true
        command:
            - test
            - -Dskip.debugVariants=true
            - -Dskip.flavor.unrestricted=true
        networks:
            - artemis
        volumes:
            - ../test-outputs/:/app/test-outputs/

    mysql:
        extends:
            file: ./mysql-for-android.yml
            service: mysql

    artemis-app:
        extends:
            file: ./artemis-for-android.yml
            service: artemis-app
        depends_on:
            mysql:
                condition: service_healthy
        env_file:
            - ./artemis/config/artemis_e2e_config.env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "8080:8080"
        expose:
            - "5005"
        networks:
            - artemis

    artemis-app-setup:
        image: ellerbrock/alpine-bash-curl-ssl:latest
        depends_on:
            artemis-app:
                condition: service_healthy
        volumes:
            - ./artemis/create_test_users.sh:/create_test_users.sh
        entrypoint: /bin/bash -c "/bin/bash /create_test_users.sh artemis-app:8080"
        networks:
            - artemis

networks:
    artemis:
        driver: "bridge"
        name: artemis

