# ----------------------------------------------------------------------------------------------------------------------
# Configured Artemis service - with volumes and production env vars
# ----------------------------------------------------------------------------------------------------------------------

services:
    artemis-app:
        extends:
            file: ./artemis-base.yml
            service: artemis-app
        volumes:
            - artemis-data:/opt/artemis/data
        # system environments are the default way for custom configuration overrides in the containerized artemis setups
        # either add them in the environments or env_file section (alternative to application-local.yml)
        env_file:
            - ./artemis/config/prod.env

volumes:
    artemis-data:
        name: artemis-data
