services:
    artemis-app:
        container_name: artemis-app
        # look in the docs for more information about how to build your Artemis code with Docker
        # https://docs.artemis.cit.tum.de/dev/setup/#
        image: ghcr.io/ls1intum/artemis:latest
        build:
            context: ..
            dockerfile: docker/artemis/Dockerfile
            pull: true
            target: runtime
        # if you need to use another port than 8080 or one fixed port for all artemis-app containers in the future
        # you will probably not be able to override this setting outside the artemis.yml
        # as stated in the docker compose docs (at least not when this was committed)
        # https://docs.docker.com/compose/compose-file/#finding-referenced-service
        healthcheck:
            test: wget -nv -t1 --spider http://localhost:8080/actuator/health || exit 1
            start_period: 600s
            interval: 1s
        # expose the port to make it reachable docker internally even if the external port mapping changes
        expose:
            - "8080"
        networks:
            - artemis

networks:
    artemis:
        driver: "bridge"
        name: artemis
