# ----------------------------------------------------------------------------------------------------------------------
# Jira base service
# ----------------------------------------------------------------------------------------------------------------------

services:
    jira:
        container_name: artemis-jira
        hostname: jira
        extra_hosts:
            - "host.docker.internal:host-gateway"
        image: ghcr.io/ls1intum/artemis-jira:9.4.3
        pull_policy: always
        volumes:
            - artemis-jira-data:/var/atlassian/application-data/jira
        ports:
            - "8081:8080"
        # expose the port to make it reachable docker internally even if the external port mapping changes
        expose:
            - "8080"
        networks:
            - artemis

networks:
    artemis:
        driver: "bridge"
        name: artemis

volumes:
    artemis-jira-data:
        name: artemis-jira-data
