# ----------------------------------------------------------------------------------------------------------------------
# MySQL base service - volume + default environment configuration
# ----------------------------------------------------------------------------------------------------------------------

services:
    mysql:
        extends:
            file: ./mysql-base.yml
            service: mysql
        pull_policy: always
        volumes:
            - artemis-mysql-data:/var/lib/mysql
        # DO NOT use this default file for production systems!
        env_file:
            - ./mysql/default.env

volumes:
    artemis-mysql-data:
        name: artemis-mysql-data
